# Generated by Django 3.1.5 on 2021-01-11 21:25

from django.db import migrations

def reorder(apps, schema_editor):
    MyModel = apps.get_model("places", "Image")
    order = 0
    for item in MyModel.objects.all():
        order += 1
        item.image_position = order
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210111_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_position']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_order',
            new_name='image_position',
        ),
        migrations.RunPython(reorder)
    ]
