# Generated by Django 3.1.5 on 2021-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210111_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='number',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция картинки'),
        ),
    ]
